#!/bin/sh
# Minimal dcm4che storescu - no OpenCV/weasis/image codec dependencies
# Usage: ./tools/storescu -c AET@host:port file.dcm [file2.dcm ...]

DIRNAME="$(cd "$(dirname "$0")" && pwd)"

if [ "x$JAVA_HOME" != "x" ]; then
    JAVA=$JAVA_HOME/bin/java
else
    JAVA="java"
fi

CP="$DIRNAME/etc/storescu/"
CP="$CP:$DIRNAME/lib/dcm4che-tool-storescu-5.32.0.jar"
CP="$CP:$DIRNAME/lib/dcm4che-core-5.32.0.jar"
CP="$CP:$DIRNAME/lib/dcm4che-net-5.32.0.jar"
CP="$CP:$DIRNAME/lib/dcm4che-tool-common-5.32.0.jar"
CP="$CP:$DIRNAME/lib/slf4j-api-2.0.9.jar"
CP="$CP:$DIRNAME/lib/logback-core-1.3.14.jar"
CP="$CP:$DIRNAME/lib/logback-classic-1.3.14.jar"
CP="$CP:$DIRNAME/lib/commons-cli-1.6.0.jar"

exec "$JAVA" -cp "$CP" org.dcm4che3.tool.storescu.StoreSCU "$@"
